// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pghxhmiiauprqrijelzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnaHhobWlpYXVwcnFyaWplbHp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4MTA0NDYsImV4cCI6MjA1MzM4NjQ0Nn0.vvFf7RCOTb09ndXEE7JejcFzjlinjWBmPCuT355BWSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);